safe: true
permalink: pretty

title: Mopidy
description: The extensible music server

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  ext:
    permalink: /ext/:title/
    output: true

defaults:
  - scope:
      path: ""
    values:
      image: /media/images/hannah-troupe-wL_w5t_OKtI-unsplash-1900x1200.jpg
